active_workspace: agro
workspaces:
  agro:
    tables:
      clima_remoto:
        name: clima_remoto
        format: CSV
        physical_path: .cache_clima_remoto.csv
        source_url: http://172.22.81.248:8080/query?view=clima_view&workspace=agro
        columns:
        - name: id_municipio
          data_type: Int64
        - name: data_coleta
          data_type: Date32
        - name: precipitacao_mm
          data_type: Float64
        - name: temperatura_c
          data_type: Float64
      safra_pq:
        name: safra_pq
        format: PARQUET
        physical_path: safra_export.parquet
        source_url: null
        columns:
        - name: id_municipio
          data_type: Int64
        - name: ano
          data_type: Int64
        - name: cultura
          data_type: Utf8
        - name: producao_ton
          data_type: Int64
      municipio:
        name: municipio
        format: CSV
        physical_path: ../dim_municipio.csv
        source_url: null
        columns:
        - name: id_municipio
          data_type: Int64
        - name: nome
          data_type: Utf8
        - name: estado
          data_type: Utf8
        - name: area_km2
          data_type: Float64
      clima:
        name: clima
        format: CSV
        physical_path: ../fato_clima.csv
        source_url: null
        columns:
        - name: id_municipio
          data_type: Int64
        - name: data_coleta
          data_type: Date32
        - name: precipitacao_mm
          data_type: Float64
        - name: temperatura_c
          data_type: Float64
      safra:
        name: safra
        format: CSV
        physical_path: ../fato_safra.csv
        source_url: null
        columns:
        - name: id_municipio
          data_type: Int64
        - name: ano
          data_type: Int64
        - name: cultura
          data_type: Utf8
        - name: producao_ton
          data_type: Int64
    views:
      clima_view: select * from clima
    published_views:
    - clima_view
  default:
    tables: {}
    views: {}
    published_views: []
